project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"  # The double asterisk tells it to check subfolders
    - "!notebooks/test_normalisation.qmd"
    - "!notebooks/megena.qmd"
    - "!notebooks/02a_msstats.qmd"
    - "!notebooks/02b_msstats_plots.qmd"
    - "!notebooks/02c_msstats_abundance.qmd"

execute:
  freeze: auto
  
website:
  title: "Millie's Proteomics Project"
  sidebar:
    style: "docked"
    contents:
      - text: "1a. Initial QC"
        file: notebooks/01a_initial_qc_spectronaut.qmd
      - text: "1b. DAA marker check"
        file: notebooks/01b_DAA_marker_check.qmd
      # - text: "MS stats "
      #   file: notebooks/02_msstats.qmd
      - text: "3. DE plots"
        file: notebooks/03_DE_plots.qmd
      - text: "4. GSEA"
        file: notebooks/04_gsea.qmd
      - text: "5. GFAP correlation"
        file: notebooks/05_gfap_correlation.qmd
      - text: "6a. Concordance between limma and MSstats"
        file: notebooks/06_msstats_limma_correlation.qmd
      - text: "6b. Pipeline-Exclusive DE Proteins: Raw & Normalised Boxplots"
        file: notebooks/06b_msstats_exclusive_DE_protein_boxplots.qmd
      - text: "7: Putative cell-cell interactions"
        file: notebooks/07_cell_interactions.qmd
      - text: "8: PPI Network analysis"
        file: notebooks/08_PPI.qmd
format:
  html:
    theme: cosmo
    df-print: paged
    toc: true
    code-fold: show
    code-copy: true