project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"  # The double asterisk tells it to check subfolders
    - "!notebooks/test_normalisation.qmd"
    - "!notebooks/megena.qmd"
    - "!notebooks/02_msstats.qmd"

website:
  title: "Millie's Proteomics Project"
  sidebar:
    style: "docked"
    contents:
      - section: "Initial QC"
        contents:
          - notebooks/01a_initial_qc_spectronaut.qmd
      - section: "DAA marker check"
        contents:
          - notebooks/01b_DAA_marker_check.qmd
      # - section: "MS stats "
      #   contents:
      #     - notebooks/02_msstats.qmd
      - section: "DE plots"
        contents: 
          - notebooks/03_DE_plots.qmd
      - section: "GSEA"
        contents:
          - notebooks/04_gsea.qmd
      - section: "GFAP correlation"
        contents:
          - notebooks/05_gfap_correlation.qmd
format:
  html:
    theme: cosmo
    df-print: paged
    toc: true
    code-fold: show
    code-copy: true