---
title: "LCM Proteomics Pipeline"
---

Documentation for Millie's Proteomics project.
This site tracks the processing of LCM samples from initial QC to Differential abundance analysis.

## Update Parameter changes (run3) - 13/03/26
Updated data filtering criteria to be more stringent:
* **Filtering Rule:** Proteins must have ≥ 50% non-missing values in at least one condition, ensuring that differential abundance analysis is on robustly detected features.

### Pipeline Stages

- [1a. Initial QC](notebooks/01a_initial_qc_spectronaut.qmd)
- [1b. DAA marker sense check](notebooks/01b_DAA_marker_check.qmd)
- [3. DE plots](notebooks/03_DE_plots.qmd)
- [4. GSEA](notebooks/04_gsea.qmd)
- [5. GFAP correlation](notebooks/05_gfap_correlation.qmd)
- [6a. MSstats limma correlation](notebooks/06_msstats_limma_correlation.qmd)
- [6b. MSstats limma comparison](notebooks/06b_msstats_exclusive_DE_protein_boxplots.qmd)
- [7. Cell-cell interactions](notebooks/07_cell_interactions.qmd)
- [8. PPI network](notebooks/08_PPI.qmd)
- [9. Tripartite Astrocyte Signature](notebooks/09_tripartite_astrocyte.qmd)
- [10. Aβ tryptic peptide correlation](notebooks/10_ab_correlation.qmd)
